######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 31 14:58:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += conn.h led.h ../msgtype.h
SOURCES += led.cpp main.cpp
