######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 30 19:12:47 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += conn.h jiaohao.h ../msgtype.h
SOURCES += jiaohao.cpp main.cpp
