######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 31 15:27:55 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += conn.h quhao.h ../msgtype.h
SOURCES += main.cpp quhao.cpp
